# Filosofía Política {#filos_pol .unnumbered}

Las notas de las primeras cuatro secciones provienen, principalmente, del libro [@lessnoff2001]; los mapas mentales se elaboraron con la aplicación [Miro](https://miro.com/es/). El incentivo de las notas es la clase Seminario de Teoría Política, que curso actualmente en la Facultad de Ciencias Políticas de la UANL, 2024.

## Varios

### Max Weber

Analiza la historia reciente de la civilización occidental a la luz de dos tipos de racionalización:

-   Racionalización de la acción: esta forma parte de la **racionalidad instrumental, la adaptación orientada de los medios a un fin**; que se pone en manifiesto en el capitalismo de la maximización de los beneficios.

-   Racionalización del pensamiento

La racionalización del pensamiento implica el desencantamiento del mundo (en *la visión del mundo cientificista la naturaleza es amoral, no hay valores objetivos*). De ahí que la principal víctima de la acción racionalizada o de la eficiencia haya sido la libertad individual y la autonomía. Los teóricos frankfurtianos, Horkheimer y Adorno, identificaban esto con la ilustración, por la tanto ellos, así como Marcus, fusionaron esta visión weberiana con su propia versión del marxismo. Bajo el signo de **racionalidad instrumental, la dominación de la naturaleza se relaciona con la irracionalidad de la comunicación de clase**.
