# Platformisation {#platfomisation}

Reporte de lectura de [@poell2019a].

> Poell, Thomas, David Nieborg, y José van Dijck. 2019. «Platformisation». *Internet Policy Review* 8 (4). <https://doi.org/10.14763/2019.4.1425>.

Los autores definen las plataformas como *"infraestructuras digitales (re) programables que facilitan y configuran interacciones personalizadas entre usuarios finales y complementadores, organizadas mediante la recopilación sistemática, el procesamiento algorítmico, la monetización y la circulación de datos"*. La platformización se entiende como la tendencia económica y tecnológica de transformar actividades tradicionales en ecosistemas digitales intermediados por una plataforma que extrae valor de las interacciones entre sus usuarios.

Ejemplos de plataformas:

- Uber no posee autos; conecta conductores con pasajeros.
- Airbnb no tiene hoteles; conecta anfitriones con viajeros.
- YouTube no produce la mayoría de sus videos; conecta creadores con espectadores y anunciantes.
- Google Maps: apps como Uber, Cabify, Uber eats o ambulancias privadas, operan sobre la API de esta plataforma; estas aplicaciones dependen de esta plataforma para operar. En cuanto al comercio, los restaurantes dependen, en gran medida, de la visibilidad y la reputación en la app de Google.

Se observa una simultanea "platformización de las infraestructuras" y "una infraestructuralización de las plataformas", es decir, grandes empresas de plataformas han surgido como el equivalente moderno de los monopolios del ferrocarril, el teléfono y la electricidad de inicios del siglo XX [@plantin2016].

Riesgos:

- Perdida de soberanía: plataformas como Twitter o Tiktok influyen, mediante algoritmos, no solo en lo que ve la ciudadanía al priorizar ciertos contenidos, sino también en que versión de la verdad es la que se debe ver.
- Cuándo una plataforma tiene una caída, genera afectación mundial. Como la caída de windows o la AWS de años pasados.
- Precarización del trabajo, como en el caso de Uber, Rappi o Didi.
- Subdivisión del trabajo en microtareas, como en el caso de la enseñanza en la que los métodos de enseñanza se supeditan a los LMS (*Learning Management Systems*), como Google Classroom, Moodle o Canvas.
- Posición desigual de poder.

Las plataformas pueden pasar de ser una herramienta a convertirse en el medio en el que vivimos, como el agua para los peces.
