# Coyuntura {#coyuntura1}

## Concepciones de la realidad social y de su conocimiento

> Notas del capítulo *Cuestiones epistémicas y teóricas* del libro [@osorio2019].

La idea del conocimiento está determinada por nuestra concepción de la realidad social:

-   Empirismo: la realidad social es lo inmediatamente dado, lo que percibimos con nuestros sentidos. La realidad social se nos presenta tal como es. Por ello, el grito de guerra de todo empirismo es “ir a la realidad” para conocerla. La ingenuidad empirista radica en suponer, primero, que podemos conocer la realidad social por simples observaciones. Su segundo error consiste en asumir que la realidad social está lista para ser conocida por esas simples observaciones.

-   Marxismo: la realidad social se presenta de manera distorsionada: es más lo que oculta que lo que devela. Ello es resultado del fetichismo que el capitalismo impone a la vida humana, de ahí que sea la opacidad lo que prevalece. En el mundo del capitalismo se tiene un doble proceso: ocultar relaciones sociales de explotación y dominio; y, crear una nueva realidad social, un mundo en apariencia de hombres libres e iguales; lo que en materia de conocimiento plantea la deconstrucción de lo creado y la develación de lo que oculta.

La sociedad se nos presenta en lo inmediatamente perceptible como un mero agregado de individuos. Son estos, se postula, los que tienen consistencia real, porque son los individuos los que razonan, actúan y deciden. Por lo tanto, si se quiere entender lo social y la sociedad, el punto de partida debe ser el individuo. Sin embargo las decisiones y la acción de los individuos se realizan en contextos que las limitan y acotan: las opciones posibles y las decisiones razonables de los individuos siempre se realizan en el contexto de las relaciones sociales en las que esos individuos se inscriben, son dichas relaciones las que definen los espacios sociales de las limitadas opciones reales de las que disponen, no de las deseables.

Sólo a través de interpretaciones que vayan más allá de lo inmediato podremos comprender y organizar lo perceptible. Por ello se hace necesario contar con propuestas explicativas que nos ofrezcan una visión de la organización de la sociedad, de sus procesos, movimientos y convulsiones.

Desde el positivismo, el término “totalidad” se presenta como sinónimo de “completitud”, es decir, como una pretensión de conocerlo todo. Pero los objetivos de un conocimiento desde la totalidad son otros: se trata de establecer las actividades y procesos que articulan y organizan la vida en sociedad en un momento o periodo determinado.

> Dicho de manera simple, conocer el bosque puede ser asumido como “conocer todo”, cada árbol, el tipo de raíces que tienen, las hojas y sus variadas formas, las plagas que los asolan, las lombrices y gusanos bajo tierra, etcétera. Pero esto es imposible porque cuando vamos terminando el estudio de todo, las primeras partes estudiadas ya habrán cambiado por el simple paso del tiempo. Pero se puede tener una noción del bosque (“conocer el todo”) en un periodo determinado, sin necesidad de un conocimiento nominal y exhaustivo de todo lo antes señalado inscrito en el bosque.

## La lógica del capital

Si hablamos de nuestro tiempo es razonable señalar que la lógica del capital es la actividad que unifica la vida societal, la que organiza, articula, jerarquiza y da sentido a nuestra sociedad y a entidades como el mercado mundial o el sistema mundial capitalista.

Lo concreto es que hoy la inmensa mayoría de las personas sólo disponen de su fuerza de trabajo para sobrevivir, misma que venden en el mercado a cambio de un salario, y de este modo acceden a alimentos, vestuario y medicinas.

En la democracia, el voto de los empresarios es un voto que se multiplica por la capacidad de ganar o coaccionar el voto de miles de otros ciudadanos. El Estado de derecho, las leyes prevalecientes y los distintos poderes del Estado se encargan de que nada se salga de los límites de lo permitido.

> En tiempos de convulsiones sociales, los individuos tienden a reconocerse como miembros de entidades sociales mayores, así sean clases sociales o fracciones de la sociedad; y el Estado o su aparato inclinan a dichas clases o fracciones a presentarse y a actuar como lo que son esencialmente: entidades que encarnan y concentran la lucha de clases.

## La realidad social

La realidad social es entender que ésta se encuentra en permanente movimiento, que nunca está quieta, que es un ser siendo, que lo que ayer parecía inerte hoy está en ebullición. Por esta razón la realidad social es un constante proceso, un devenir histórico que sólo el conocimiento puede explicar. Toda idea de coagulación en esta fluidez es perecedera y destinada a ser superada.

Una acusación recurrente al marxismo es que constituye una teoría determinista, incapaz de comprender situaciones con tingentes,aquellas que se apartan del libreto previamente establecido.

-   Determinismo: en los procesos sociales sólo existe una y nada más que una salida o solución. O que sólo puede acontecer una única solución.

-   Determinación: en la vida en sociedad y sus procesos operan legalidades y tendencias, y que pueden ocurrir muchas salidas y muchas soluciones, pero no que puede ocurrir cualquier cosa.

> “lo concreto es concreto porque es la síntesis de múltiples determinaciones, por lo tanto unidad de lo diverso”, se refiere a un conocimiento que tiende a capturar, algún proceso de la realidad social que incorpora una gran cantidad de relaciones y de procesos que la constituyen y redefinen en su dinámica, permitiéndonos su mejor comprensión.

Niveles de análisis en el marxismo: modo de producción, sistema mundial, formas de capitalismo, patrones de reproducción de capital, formaciones económico-sociales y coyuntura.

> El análisis de coyuntura debe alimentarse de todos esos basamentos para efectivamente alcanzar concreción.

### Modo de producción capitalista

-   El grueso de la producción es producción de mercancías.

-   El valor producido en una jornada de trabajo siempre debe tender a ser superior al valor diario de la fuerza de trabajo.

-   El capitalismo, a este nivel, debe encontrar una forma en que los asalariados participen de manera activa en la conformación del mercado, allí donde las mercancías se intercambian por dinero.

-   Se crean las condiciones que, por un lado, obligan a los trabajadores a salir diariamente a vender su fuerza de trabajo, y por otro, permite a los capitales apropiarse del plusvalor generado.

-   Para incrementar la plusvalía, los capitales invierten en nuevos equipos, maquinarias y conocimientos, a fin de reducir el tiempo de trabajo necesario, aquel en donde los productores producen valores equivalentes al valor diario de su fuerza de trabajo.

-   Las crisis económicas alientan la lucha entre capitales, con miras a decidir quiénes sufrirán los mayores costos. Pero también alientan la lucha entre el capital y el trabajo, al acentuarse los mecanismos que buscan incrementar la tasa de explotación, desde las bajas salariales hasta el incremento de las jornadas laborales y la intensificación del trabajo.) Todas estas luchas y contradicciones se generan por la propia lógica que subyace tras el apetito del capital por incrementar la plusvalía y las ganancias. Es por ésto que Marx indica que el enemigo del capital es el mismo capital.

Capitalismo desarrollado:

-   Es un capitalismo autocentrado.

-   Tiende a crecer el tiempo de trabajo excedente por una reducción real de tiempo de trabajo necesario. De esta forma se logra una ecuación nada sencilla; que crezca la plusvalía y que el consumo de los asalariados se sostenga o incluso se incremente. Para sostener esta situación, en el capitalismo desarrollado se gasta en generar conocimientos, y en la producción regular y permanente de nuevos equipos, maquinarias y herramientas. Esto propicia que la innovación incluso de nuevos bienes de consumo se exprese como una tendencia regular.

-   Parte sustantiva de esas privilegiadas condiciones materiales de infraestructura, de políticas de bienestar y de salarios, reposaba en la apropiación de valor que los capitales y los Estados de las economías desarrolladas extraen de las economías dependientes y sus trabajadores. Pero de manera clara se debe señalar que no son los trabajadores del capitalismo desarrollado los que explotan a los del capitalismo dependiente. Son los capitales y los Estados de los primeros los que explotan.

Capitalismo dependiente

-   Capitalismo descentrado. Ello propicia una estructura productiva concentrada en la producción de materias primas y alimentos, y algunas ramas e industrias abocadas a la producción de bienes de consumo.

-   La capacidad de competencia de este capitalismo en los mercados exteriores reposa en pagar salarios por debajo del valor de la fuerza de trabajo o superexplotación.

-   La precariedad y la subcontratación son la norma en los empleos en este tipo de economías, no sólo en tiempos de crisis, sino de forma regular.

-   El Estado en el capitalismo dependiente es una entidad subsoberana, sometida a condiciones de subordinación en el campo exterior. En el plano interno tienden a prevalecer las formas autoritarias de gobierno

-   En este capitalismo lo que prevalece es el “desarrollo del subdesarrollo”, lo que pone de manifiesto que en su dinámica, más que aproximarsea las metas y estadios del capitalismo desarrollado, el capitalismo dependiente camina alejándose de aquéllos.

-   Las regiones dependientes del sistema mundial capitalista se constituyen en el eslabón débil de la dominación imperialista prevaleciente.
